### ISSUE TITLE
Composed Datasources

### ISSUE THREAD

**Issue by inPhilly** [square/PJFDataSource#3]
This looks like a great tool, but I am wondering if there is a way to handle composed datasources (i.e. a dataSource made up of other datasSources, each representing, perhaps, a section)?

**Comment by inPhilly** [comment]
Any thoughts on this?

**Comment by mthole-old** [comment]
@mommyme This is definitely something that can be done, but is not supported directly in PJFDataSource today.

The original inspiration for this project, Apple's Advanced Collection View sample code, actually has composed data sources like you're describing. When implementing PJFDataSource I intentionally omitted composed data sources in favor of simplicity.

I'm curious about your use case. You can of course have multiple table view sections in a single PJFDataSource today. But, I'm guessing that you want to load your sections from different backend endpoints, each with its own PJFDataSource?

**Comment by inPhilly** [comment]
@mthole I have a different datasource for each Entity type, where I customize the cells for that Entity, have a NSFetchedResultsController as my 'items' source, etc. There are a couple cases - for instance my 'Setup Data' controller, where I used a composed datasource. Each 'section' has its own datasource with its own NSFetchedResultsController which manages that adding and deleting of cell rows. Right now I am using Advanced Collection View code, but since I had to alter it for a NSFetchedResultsController datasource (and I am probably not the best programmer), this code feels so unwieldy to me. Does your code handle a datasource that uses a NSFetchedResultsController? I looked but didn't see an example of that. Also, do you have a better way to approach the 'Setup Data' scenario I described above using your PJFDataSource? I really need some code that works well (I feel like I am having threading issues  using the Advanced Collection View code) and is simple enough for me to understand, yet can also handle NSFetchedResultsController dataSources and has a way I can 'compose' things without too much difficulty. Even if I end up using simple Array DataSources for the Setup Data controller, I still need NSFetchedResultsController sources for my main controllers (which use only one datasource each). I would appreciate any thoughts you have on this because I am REALLY ready to ditch Advanced Collection View and I would love if PJFDataSource was a viable option for me. Thanks in advance. Jen

**Comment by inPhilly** [comment]
Sorry, it was probably too much of a question. I am trying to focus on seeing if I can use PJFDataSource with a NSFetchedResultsController right now.
